### ISSUE TITLE
Blender 2.90 BlenderRenderController.exe errors on opening save file

### ISSUE THREAD

**Issue by badbud65** [Isti115/BlenderRenderController#17]
I get the following Script error when opening a file saved with Blender 2.90

![BlenderRenderController_Error](https://user-images.githubusercontent.com/4669127/92751900-55426700-f380-11ea-9ae2-3138744dfa94.png)
**Error Reads**

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: StandardOut has not been redirected or the process hasn't started yet.
   at System.Diagnostics.Process.get_StandardOutput()
   at BlenderRenderController.MainForm.DoReadBlenderData()
   at BlenderRenderController.MainForm.blendFileBrowseButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************

mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlenderRenderController
    Assembly Version: 0.5.0.0
    Win32 Version: 0.5.0.0
    CodeBase: file:///E:/BlenderRenderController/BlenderRenderController.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Comment by badbud65** [comment]
Works as normal with LTS Release 2.83.6

**Comment by isti115** [comment]
Thanks for reporting the issue!
I've seen the notification, but didn't really have time to look into this currently due to university related reasons, but I hope to have capacity to create a fix for it in a few weeks!

**Comment by badbud65** [comment]
No worries I'll stick with the LTS 2.83.6, nothing much has changed in 2.9 for video rendering, if anything but a few fixes.

**Comment by isti115** [comment]
Sorry for the huge delay, I've got really overwhelmed by all the university related obligations, but as this semester is coming to an end I really hope that I'll have a day [I think that it should be enough to figure this out, I just need to find a Windows computer.] that I can allocate to this issue after submitting my assignments until their deadlines and before the new tasks start appearing!

**Comment by isti115** [comment]
Hi @badbud65! Once again I apologize for not dealing with this issue for so long, but finally last week I have found enough time to boot into Windows and examine the situation. What I noticed is that the error message has appeared for me as well, but after a bit of troubleshooting I realized that it was due to the fact, that a folder name in the installation path of blender has changed from `blender` to `blender 2.9` or something like this. Once I have updated my environmental variable to reflect the change, the program has begun working correctly again without any actual modification to the source code.

After figuring this out I have made another interesting observation, because I have launched the test with only four instances, but it still managed to saturate my eight thread CPU, which made me wonder if meanwhile multithreaded rendering has been implemented natively, so I looked it up and it turns out that this program has now less of a reason to exist, but since it can still be useful for rendering on multiple machines or things like that I will probably leave it up here. :)

Thanks again for reporting the issue and sorry for taking so long with figuring it out!
